"use client";
import { useCallback, useEffect, useState } from "react";
import { RevenueConnectors } from "./revenue-connectors";
import type { RevenueEntry } from "@/lib/revenue/schema";
import styles from "./revenue.module.css";
type Payload = { currency: string; summary: { adSpend:number|null; afterAdSpend:number|null; sales:number; refunds:number; costs:number; netRevenue:number; netAfterCosts:number; excluded:number; sources:Array<{label:string;value:number}>; labels:Array<{label:string;value:number}> }; entries:RevenueEntry[]; count:number; canEdit:boolean; batches:Array<{id:string;source:string;name:string;row_count:number;created_at:string;rolled_back_at:string|null}> };
export function LeadRevenuePage({ range }: { range: { from:string; to:string } }) {
  const [year,setYear]=useState(""),[month,setMonth]=useState(""),[data,setData]=useState<Payload|null>(null),[error,setError]=useState("");
  const from=year ? `${year}-${month||"01"}-01` : range.from;
  const to=year ? new Date(Date.UTC(Number(year),month?Number(month):12,0)).toISOString().slice(0,10) : range.to;
  const fetchData=useCallback(async()=>{ const params=new URLSearchParams();if(from)params.set("from",from);if(to)params.set("to",to);const r=await fetch(`/api/revenue?${params}`);const result=await r.json();if(!r.ok)throw new Error(result.error);return result as Payload; },[from,to]);
  const load=useCallback(async()=>{setData(await fetchData());setError("");},[fetchData]);
  useEffect(()=>{let active=true;void fetchData().then(result=>{if(active){setData(result);setError("");}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[fetchData]);
  const money=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:data?.currency||"GBP",maximumFractionDigits:2}).format(n);
  const years=Array.from({length:new Date().getFullYear()-2000+2},(_,i)=>String(2000+i));
  return <div className={styles.root}><div className={styles.heading}><span className="eyebrow">REVENUE & COSTS</span><h2>Money collected, beyond the pipeline</h2><p>Actual receipts from Stripe and external sales. GHL opportunity value is tracked separately. Amounts are grouped by payment/refund date.</p></div><div className={styles.actions}><label>Year<select value={year} onChange={e=>setYear(e.target.value)}><option value="">Use report date filter</option>{years.map(y=><option key={y}>{y}</option>)}</select></label><label>Month<select disabled={!year} value={month} onChange={e=>setMonth(e.target.value)}><option value="">Full year</option>{Array.from({length:12},(_,i)=><option key={i} value={String(i+1).padStart(2,"0")}>{new Date(2026,i,1).toLocaleString("en-GB",{month:"long"})}</option>)}</select></label><button onClick={()=>void load().catch(e=>setError(e.message))}>Refresh report</button></div>{error&&<p className={styles.notice} role="alert">{error}</p>}
    {data&&<><div className={styles.grid}>{[["Collected sales",data.summary.sales],["Refunds",data.summary.refunds],["Net collected revenue",data.summary.netRevenue],["External costs",data.summary.costs],["After external costs",data.summary.netAfterCosts],["Imported ad spend",data.summary.adSpend],["After costs & imported ads",data.summary.afterAdSpend]].map(([label,value])=><article className={styles.card} key={String(label)}><span className="eyebrow">{label}</span><div className={styles.value}>{value===null?"—":money(Number(value))}</div></article>)}</div><p>After external costs excludes advertising spend, processing fees and costs not entered here. {data.summary.excluded>0?`${data.summary.excluded} entries in other currencies excluded; no currency conversion is applied.`:""}</p><div className={styles.grid}>{[["Revenue by source",data.summary.sources],["Costs by label",data.summary.labels]].map(([title,raw])=>{const rows=raw as Array<{label:string;value:number}>;const max=Math.max(1,...rows.map(r=>Math.abs(r.value)));return <article key={String(title)} className={styles.card}><h3>{String(title)}</h3>{rows.length?rows.map(row=><div key={row.label}><p>{row.label.replaceAll("_"," ")}</p><div className={styles.bar}><span style={{width:`${Math.abs(row.value)/max*100}%`}}/><b>{money(row.value)}</b></div></div>):<p>No entries in this period.</p>}</article>;})}</div><article className={styles.card}><h3>Recent receipts & costs</h3><p>Showing up to 100 of {data.count.toLocaleString()} entries.</p><div className={styles.scroll}><table><thead><tr><th>Date</th><th>Entry</th><th>Type</th><th>GHL opportunity</th><th>Amount</th></tr></thead><tbody>{data.entries.map(e=><tr key={e.entry_key}><td>{e.entry_date}</td><td>{e.label}<br/><small>{e.external_id}</small></td><td>{e.kind}</td><td>{e.opportunity_id||"Unlinked"}</td><td>{new Intl.NumberFormat("en-GB",{style:"currency",currency:e.currency}).format(e.amount_minor/10**(new Intl.NumberFormat("en",{style:"currency",currency:e.currency}).resolvedOptions().maximumFractionDigits??2))}</td></tr>)}</tbody></table></div></article><details className={styles.card}><summary>Import history & rollback</summary><p>Rolling back a batch restores earlier versions of corrected entries. Stripe batches are managed by the Stripe sync.</p><div className={styles.scroll}><table><thead><tr><th>Import</th><th>Date</th><th>Rows</th><th>Status</th></tr></thead><tbody>{data.batches.map(b=><tr key={b.id}><td>{b.name}</td><td>{new Date(b.created_at).toLocaleString()}</td><td>{b.row_count}</td><td>{b.rolled_back_at?"Rolled back":b.source!=="stripe"&&data.canEdit?<button onClick={()=>{if(!window.confirm(`Roll back ${b.name} (${b.row_count} rows)? Earlier versions will be restored.`))return;void fetch(`/api/revenue/import?batch=${b.id}`,{method:"DELETE"}).then(async r=>{if(!r.ok)throw new Error("Rollback failed");await load();}).catch(e=>setError(e.message));}}>Roll back</button>:"Imported"}</td></tr>)}</tbody></table></div></details></>}
    <RevenueConnectors onImported={()=>void load().catch(e=>setError(e.message))}/>
  </div>;
}
