import { NextResponse } from "next/server";

import { createAdminClient } from "@/lib/supabase/admin";
import { computePnl, loadPnlInputs, slicePnlInputs, type PnlResult } from "@/lib/analytics/pnl-engine";

export const maxDuration = 300;

type Store = { id: string; name: string; currency: string; timezone: string | null };
type Setting = { store_id: string; enabled: boolean; webhook_url: string | null };

const dayKey = (date: Date) => date.toISOString().slice(0, 10);

const money = (value: number, currency: string) =>
  new Intl.NumberFormat("en-GB", { style: "currency", currency, maximumFractionDigits: 0 }).format(value);

const htmlEscape = (value: string) =>
  value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");

function renderHtml(input: {
  name: string;
  currency: string;
  from: string;
  to: string;
  netSales: number;
  grossProfit: number;
  marketingSpend: number;
  netProfit: number;
  profitLabel: string;
  orders: number;
  averageOrderValue: number;
  chart: Array<{ date: string; netSales: number; grossProfit: number; marketingSpend: number; netProfit: number }>;
}) {
  const cards = [
    ["Net sales", money(input.netSales, input.currency)],
    ["Gross profit", money(input.grossProfit, input.currency)],
    ["Marketing", money(input.marketingSpend, input.currency)],
    [input.profitLabel, money(input.netProfit, input.currency)],
    ["Orders", input.orders.toLocaleString("en-GB")],
    ["Average order value", money(input.averageOrderValue, input.currency)],
  ];
  const rows = input.chart.map((row) =>
    "<tr>" +
    "<td style=\"padding:11px 8px;border-bottom:1px solid #e9ecf3\">" + row.date + "</td>" +
    "<td style=\"padding:11px 8px;border-bottom:1px solid #e9ecf3;text-align:right\">" + money(row.netSales, input.currency) + "</td>" +
    "<td style=\"padding:11px 8px;border-bottom:1px solid #e9ecf3;text-align:right;color:#0f9d72\">" + money(row.grossProfit, input.currency) + "</td>" +
    "<td style=\"padding:11px 8px;border-bottom:1px solid #e9ecf3;text-align:right;color:#e66b51\">" + money(row.marketingSpend, input.currency) + "</td>" +
    "<td style=\"padding:11px 8px;border-bottom:1px solid #e9ecf3;text-align:right\">" + money(row.netProfit, input.currency) + "</td>" +
    "</tr>",
  ).join("");

  return "<!doctype html><html><body style=\"margin:0;background:#f6f7fb;font-family:Arial,sans-serif;color:#17213a\">" +
    "<div style=\"max-width:700px;margin:24px auto;background:white;border-radius:18px;overflow:hidden\">" +
    "<div style=\"padding:30px;background:#11182b;color:white\"><div style=\"font-size:12px;letter-spacing:2px;color:#bcb3ff;font-weight:700\">SPINE · WEEKLY REPORT</div><h1 style=\"margin:10px 0 4px;font-size:28px\">" + htmlEscape(input.name) + "</h1><div style=\"color:#c5cad8\">" + input.from + " – " + input.to + "</div></div>" +
    "<div style=\"padding:24px\"><table width=\"100%\" cellspacing=\"8\"><tr>" +
    cards.slice(0, 3).map(([label, value]) => "<td width=\"33%\" style=\"border:1px solid #e7eaf3;border-radius:11px;padding:14px\"><div style=\"font-size:10px;color:#75809a;font-weight:700;text-transform:uppercase\">" + label + "</div><div style=\"font-size:20px;font-weight:700;margin-top:7px\">" + value + "</div></td>").join("") +
    "</tr><tr>" +
    cards.slice(3).map(([label, value]) => "<td width=\"33%\" style=\"border:1px solid #e7eaf3;border-radius:11px;padding:14px\"><div style=\"font-size:10px;color:#75809a;font-weight:700;text-transform:uppercase\">" + label + "</div><div style=\"font-size:20px;font-weight:700;margin-top:7px\">" + value + "</div></td>").join("") +
    "</tr></table><h2 style=\"font-size:18px;margin:26px 0 10px\">Revenue, costs and profit</h2><div style=\"font-size:12px;color:#75809a;margin-bottom:12px\"><span style=\"color:#7057eb\">● Revenue</span> &nbsp; <span style=\"color:#0f9d72\">● Gross profit</span> &nbsp; <span style=\"color:#e66b51\">● Marketing</span></div>" +
    "<table width=\"100%\" cellspacing=\"0\" style=\"font-size:12px\"><thead><tr style=\"color:#75809a;text-align:left\"><th style=\"padding:10px 8px\">Day</th><th style=\"padding:10px 8px;text-align:right\">Revenue</th><th style=\"padding:10px 8px;text-align:right\">Gross profit</th><th style=\"padding:10px 8px;text-align:right\">Marketing</th><th style=\"padding:10px 8px;text-align:right\">" + htmlEscape(input.profitLabel) + "</th></tr></thead><tbody>" +
    rows +
    "</tbody></table><p style=\"font-size:12px;color:#75809a;margin:22px 0 0\">Generated by Spine from imported Shopify, Meta, Google and Microsoft Advertising data.</p></div></div></body></html>";
}



const revenue = (result: PnlResult) => result.metrics.netProductSales - result.metrics.refunds;
const profit = (result: PnlResult) => result.metrics.netProfit ?? result.metrics.profitAfterKnownCosts;

/**
 * Sends last week's report for every store that opted in
 * (weekly_report_settings.enabled). Each store goes to its own webhook, or to
 * GHL_WEEKLY_REPORT_WEBHOOK_URL when it has none. Figures come from the same
 * P&L engine as the app, so ad spend in other currencies is converted and
 * "profit" is true net profit when every cost is known ("Profit after known
 * costs" otherwise, as on the P&L screen).
 *
 * The payload keeps its earlier field names (netSales, grossProfit,
 * marketingSpend, netProfit, chart[]) so existing GoHighLevel workflows keep
 * mapping; profitLabel and netProfitComplete say which profit it is.
 */
export async function GET(request: Request) {
  const cronSecret = process.env.CRON_SECRET?.trim();
  if (!cronSecret || request.headers.get("authorization") !== "Bearer " + cronSecret) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const globalWebhook = process.env.GHL_WEEKLY_REPORT_WEBHOOK_URL?.trim();
  const fallbackWebhook = globalWebhook?.startsWith("https://") ? globalWebhook : null;
  const supabase = createAdminClient();
  const [{ data: storeData, error: storesError }, { data: settingData, error: settingsError }] = await Promise.all([
    supabase.from("stores").select("id,name,currency,timezone"),
    supabase.from("weekly_report_settings").select("store_id,enabled,webhook_url").eq("enabled", true),
  ]);
  if (storesError || settingsError) return NextResponse.json({ error: (storesError ?? settingsError)!.message }, { status: 500 });
  const settings = new Map(((settingData ?? []) as Setting[]).map((setting) => [setting.store_id, setting]));

  const yesterday = new Date();
  yesterday.setUTCDate(yesterday.getUTCDate() - 1);
  const weekStart = new Date(yesterday);
  weekStart.setUTCDate(weekStart.getUTCDate() - 6);
  const from = dayKey(weekStart);
  const to = dayKey(yesterday);
  const delivered: Array<{ storeId: string; storeName: string }> = [];
  const failed: Array<{ storeId: string; storeName: string; error: string }> = [];

  for (const store of (storeData ?? []) as Store[]) {
    const setting = settings.get(store.id);
    const webhookUrl = setting?.webhook_url ?? fallbackWebhook;
    if (!setting || !webhookUrl) continue;
    try {
      const loaded = await loadPnlInputs(supabase, store, { from, to });
      if (!loaded.ok) throw new Error(loaded.error);
      const week = computePnl(loaded.inputs, store);
      const chart = Array.from({ length: 7 }, (_, index) => {
        const date = new Date(weekStart);
        date.setUTCDate(weekStart.getUTCDate() + index);
        const key = dayKey(date);
        const day = computePnl(slicePnlInputs(loaded.inputs, store, { from: key, to: key }), store);
        return { date: key, netSales: revenue(day), grossProfit: day.metrics.grossProfit, marketingSpend: day.metrics.marketingSpend, netProfit: profit(day) };
      });
      const netProfitComplete = week.availability.netProfit;
      const profitLabel = netProfitComplete ? "Net profit" : "Profit after known costs";
      const metrics = {
        netSales: revenue(week),
        grossProfit: week.metrics.grossProfit,
        marketingSpend: week.metrics.marketingSpend,
        netProfit: profit(week),
        orders: week.metrics.orders,
        averageOrderValue: week.metrics.orders ? revenue(week) / week.metrics.orders : 0,
        profitLabel,
        netProfitComplete,
      };
      const payload = {
        event: "spine.weekly_overview_report",
        generatedAt: new Date().toISOString(),
        report: {
          store: { id: store.id, name: store.name, currency: store.currency, timezone: store.timezone ?? "UTC" },
          period: { from, to },
          metrics,
          chart,
          html: renderHtml({ name: store.name, currency: store.currency, from, to, ...metrics, chart }),
        },
      };
      const response = await fetch(webhookUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json", "User-Agent": "Spine-Weekly-Report/1.0" },
        body: JSON.stringify(payload),
        cache: "no-store",
      });
      if (!response.ok) throw new Error("Webhook returned " + response.status);
      delivered.push({ storeId: store.id, storeName: store.name });
    } catch (error) {
      failed.push({ storeId: store.id, storeName: store.name, error: error instanceof Error ? error.message : "Unknown error" });
    }
  }

  return NextResponse.json({ period: { from, to }, delivered, failed }, { status: failed.length ? 207 : 200 });
}
