import { NextResponse } from "next/server";

import { createReportingClient } from "@/lib/analytics/reporting-refresh";

type Store = { id: string; name: string; currency: string; timezone: string | null };
type SalesDay = { sales_date: string; net_sales: string; gross_profit: string; orders: number };

const number = (value: unknown) => {
  const parsed = Number(value ?? 0);
  return Number.isFinite(parsed) ? parsed : 0;
};

const dayKey = (date: Date) => date.toISOString().slice(0, 10);

const money = (value: number, currency: string) =>
  new Intl.NumberFormat("en-GB", { style: "currency", currency, maximumFractionDigits: 0 }).format(value);

const htmlEscape = (value: string) =>
  value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");

function renderHtml(input: {
  name: string;
  currency: string;
  from: string;
  to: string;
  netSales: number;
  grossProfit: number;
  marketingSpend: number;
  netProfit: number;
  orders: number;
  averageOrderValue: number;
  chart: Array<{ date: string; netSales: number; grossProfit: number; marketingSpend: number; netProfit: number }>;
}) {
  const cards = [
    ["Net sales", money(input.netSales, input.currency)],
    ["Gross profit", money(input.grossProfit, input.currency)],
    ["Marketing", money(input.marketingSpend, input.currency)],
    ["Net profit", money(input.netProfit, input.currency)],
    ["Orders", input.orders.toLocaleString("en-GB")],
    ["Average order value", money(input.averageOrderValue, input.currency)],
  ];
  const rows = input.chart.map((row) =>
    "<tr>" +
    "<td style=\"padding:11px 8px;border-bottom:1px solid #e9ecf3\">" + row.date + "</td>" +
    "<td style=\"padding:11px 8px;border-bottom:1px solid #e9ecf3;text-align:right\">" + money(row.netSales, input.currency) + "</td>" +
    "<td style=\"padding:11px 8px;border-bottom:1px solid #e9ecf3;text-align:right;color:#0f9d72\">" + money(row.grossProfit, input.currency) + "</td>" +
    "<td style=\"padding:11px 8px;border-bottom:1px solid #e9ecf3;text-align:right;color:#e66b51\">" + money(row.marketingSpend, input.currency) + "</td>" +
    "<td style=\"padding:11px 8px;border-bottom:1px solid #e9ecf3;text-align:right\">" + money(row.netProfit, input.currency) + "</td>" +
    "</tr>",
  ).join("");

  return "<!doctype html><html><body style=\"margin:0;background:#f6f7fb;font-family:Arial,sans-serif;color:#17213a\">" +
    "<div style=\"max-width:700px;margin:24px auto;background:white;border-radius:18px;overflow:hidden\">" +
    "<div style=\"padding:30px;background:#11182b;color:white\"><div style=\"font-size:12px;letter-spacing:2px;color:#bcb3ff;font-weight:700\">SPINE · WEEKLY REPORT</div><h1 style=\"margin:10px 0 4px;font-size:28px\">" + htmlEscape(input.name) + "</h1><div style=\"color:#c5cad8\">" + input.from + " – " + input.to + "</div></div>" +
    "<div style=\"padding:24px\"><table width=\"100%\" cellspacing=\"8\"><tr>" +
    cards.slice(0, 3).map(([label, value]) => "<td width=\"33%\" style=\"border:1px solid #e7eaf3;border-radius:11px;padding:14px\"><div style=\"font-size:10px;color:#75809a;font-weight:700;text-transform:uppercase\">" + label + "</div><div style=\"font-size:20px;font-weight:700;margin-top:7px\">" + value + "</div></td>").join("") +
    "</tr><tr>" +
    cards.slice(3).map(([label, value]) => "<td width=\"33%\" style=\"border:1px solid #e7eaf3;border-radius:11px;padding:14px\"><div style=\"font-size:10px;color:#75809a;font-weight:700;text-transform:uppercase\">" + label + "</div><div style=\"font-size:20px;font-weight:700;margin-top:7px\">" + value + "</div></td>").join("") +
    "</tr></table><h2 style=\"font-size:18px;margin:26px 0 10px\">Revenue, costs and profit</h2><div style=\"font-size:12px;color:#75809a;margin-bottom:12px\"><span style=\"color:#7057eb\">● Revenue</span> &nbsp; <span style=\"color:#0f9d72\">● Gross profit</span> &nbsp; <span style=\"color:#e66b51\">● Marketing</span></div>" +
    "<table width=\"100%\" cellspacing=\"0\" style=\"font-size:12px\"><thead><tr style=\"color:#75809a;text-align:left\"><th style=\"padding:10px 8px\">Day</th><th style=\"padding:10px 8px;text-align:right\">Revenue</th><th style=\"padding:10px 8px;text-align:right\">Gross profit</th><th style=\"padding:10px 8px;text-align:right\">Marketing</th><th style=\"padding:10px 8px;text-align:right\">Net profit</th></tr></thead><tbody>" +
    rows +
    "</tbody></table><p style=\"font-size:12px;color:#75809a;margin:22px 0 0\">Generated by Spine from imported Shopify, Meta and Google Ads data.</p></div></div></body></html>";
}

export async function GET(request: Request) {
  const cronSecret = process.env.CRON_SECRET?.trim();
  if (!cronSecret || request.headers.get("authorization") !== "Bearer " + cronSecret) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const webhookUrl = process.env.GHL_WEEKLY_REPORT_WEBHOOK_URL?.trim();
  if (!webhookUrl || !webhookUrl.startsWith("https://")) {
    return NextResponse.json({ error: "Set GHL_WEEKLY_REPORT_WEBHOOK_URL to an HTTPS GoHighLevel webhook" }, { status: 503 });
  }

  const supabase = createReportingClient();
  const { data: storeData, error: storesError } = await supabase.from("stores").select("id,name,currency,timezone");
  if (storesError) return NextResponse.json({ error: storesError.message }, { status: 500 });

  const yesterday = new Date();
  yesterday.setUTCDate(yesterday.getUTCDate() - 1);
  const weekStart = new Date(yesterday);
  weekStart.setUTCDate(weekStart.getUTCDate() - 6);
  const from = dayKey(weekStart);
  const to = dayKey(yesterday);
  const delivered: Array<{ storeId: string; storeName: string }> = [];
  const failed: Array<{ storeId: string; storeName: string; error: string }> = [];

  for (const store of (storeData ?? []) as Store[]) {
    try {
      const [salesResult, metaResult, googleResult] = await Promise.all([
        supabase.from("shopify_sales_daily").select("sales_date,net_sales,gross_profit,orders").eq("store_id", store.id).gte("sales_date", from).lte("sales_date", to).order("sales_date", { ascending: true }),
        supabase.from("meta_ad_insights_daily").select("date_start,spend,currency").eq("store_id", store.id).gte("date_start", from).lte("date_start", to),
        supabase.from("google_ads_insights_daily").select("insight_date,spend,currency").eq("store_id", store.id).gte("insight_date", from).lte("insight_date", to),
      ]);
      const error = salesResult.error ?? metaResult.error ?? googleResult.error;
      if (error) throw error;

      const salesByDate = new Map<string, SalesDay>();
      for (const row of (salesResult.data ?? []) as SalesDay[]) salesByDate.set(row.sales_date, row);
      const spendByDate = new Map<string, number>();
      for (const row of metaResult.data ?? []) {
        const date = typeof row.date_start === "string" ? row.date_start : "";
        if (date && row.currency === store.currency) spendByDate.set(date, (spendByDate.get(date) ?? 0) + number(row.spend));
      }
      for (const row of googleResult.data ?? []) {
        const date = typeof row.insight_date === "string" ? row.insight_date : "";
        if (date && row.currency === store.currency) spendByDate.set(date, (spendByDate.get(date) ?? 0) + number(row.spend));
      }

      const chart = Array.from({ length: 7 }, (_, index) => {
        const date = new Date(weekStart);
        date.setUTCDate(weekStart.getUTCDate() + index);
        const key = dayKey(date);
        const sales = salesByDate.get(key);
        const netSales = number(sales?.net_sales);
        const grossProfit = number(sales?.gross_profit);
        const marketingSpend = spendByDate.get(key) ?? 0;
        return { date: key, netSales, grossProfit, marketingSpend, netProfit: grossProfit - marketingSpend, orders: sales?.orders ?? 0 };
      });
      const totals = chart.reduce((total, row) => ({
        netSales: total.netSales + row.netSales,
        grossProfit: total.grossProfit + row.grossProfit,
        marketingSpend: total.marketingSpend + row.marketingSpend,
        netProfit: total.netProfit + row.netProfit,
        orders: total.orders + row.orders,
      }), { netSales: 0, grossProfit: 0, marketingSpend: 0, netProfit: 0, orders: 0 });
      const metrics = { ...totals, averageOrderValue: totals.orders ? totals.netSales / totals.orders : 0 };
      const chartPayload = chart.map(({ orders: _orders, ...row }) => row);
      const payload = {
        event: "spine.weekly_overview_report",
        generatedAt: new Date().toISOString(),
        report: {
          store: { id: store.id, name: store.name, currency: store.currency, timezone: store.timezone ?? "UTC" },
          period: { from, to },
          metrics,
          chart: chartPayload,
          html: renderHtml({ name: store.name, currency: store.currency, from, to, ...metrics, chart: chartPayload }),
        },
      };
      const response = await fetch(webhookUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json", "User-Agent": "Spine-Weekly-Report/1.0" },
        body: JSON.stringify(payload),
        cache: "no-store",
      });
      if (!response.ok) throw new Error("GoHighLevel webhook returned " + response.status);
      delivered.push({ storeId: store.id, storeName: store.name });
    } catch (error) {
      failed.push({ storeId: store.id, storeName: store.name, error: error instanceof Error ? error.message : "Unknown error" });
    }
  }

  return NextResponse.json({ period: { from, to }, delivered, failed }, { status: failed.length ? 207 : 200 });
}
